name: Deploy GitHub Pages (MkDocs Material)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-mkdocs"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MkDocs Material
        run: |
          pip install mkdocs mkdocs-material
      - name: Build docs
        run: mkdocs build --clean --site-dir site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
