name: Trivy Scan
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '1'
